### ISSUE TITLE
Chess game Not running

### ISSUE THREAD

**Issue by jbookwal** [JustinBird/ChessGame#1]
I downloaded all of your files and added them to my project.  I ran the test and it outputted a bunch of numbers and ran successfully.  When I took out the tests and commented out main It did not pull up a chess board but just a blank screen and the numbers again. I also can't find ofxNetworks.  I am not sure what is going wrong.  Are you able to help me out please?

**Comment by JustinBird** [comment]
I'm not sure if you are using visual studio, but if not, I would recommend it and it's also what I am most familiar with.

ofxNetwork is a standard openFrameworks library and should be included when using the project generator. ofxUIUtils 

If you want, I can make a more comprehensive readme detailing setup if this doesn't work.

**Comment by jbookwal** [comment]
I am currently running Xcode with open frame works.  Is there any difference?

**Comment by JustinBird** [comment]
Everything should work with Xcode just find, I am just not as familiar with it. Were you able to successfully generate the project with ofxNetwork and ofxUIUtils?

**Comment by jbookwal** [comment]
Im not sure what the network is. I didn’t see anything to download. I did get it to successfully run but it does not pull up the screen for chess. Just a blank grey screen.When you ran the test did a bunch of number appear in the output box?

-Jacob

**Comment by jbookwal** [comment]
If you want I can send you my project and see if you know what’s wrong.

-Jacob

**Comment by JustinBird** [comment]
For now, I recommend completely deleting the test folder as it's not necessary to run the game and can interfere with it running correctly. 

ofxNetwork is a standard openFrameworks library. ofXNetwork has to be included in the project through the project generator with ofxUIUtils. Did you generate the project using the openFrameworks project generator? If you don't the project will not run correctly.

I don't have an apple computer so I can't run Xcode and know very little about it so I can't do much if you send me your project.

**Comment by jbookwal** [comment]
Ok I will try that and get back to you.

-Jacob

**Comment by jbookwal** [comment]
It still won't run after I put in the ofXnetwork files.  Are you able to just post directions or the file with just the offline game please?

**Comment by JustinBird** [comment]
Can you try and run one of the openFrameworks examples? They are located in your openFrameworks download location under the examples folder.

**Comment by jbookwal** [comment]
I just tried they work

**Comment by JustinBird** [comment]
Just to be clear have you done all of the following:
- Installed openFrameworks
- Downloaded the project
- Delete the tests
- Download ofxUIUtils
- Generate the project using the openFrameworks project generator (including ofxNetwork and ofxUIUtils in the add on section)

Also in your original post you said:
> When I took out the tests and commented out main It did not pull up a chess board but just a blank screen and the numbers again.

If you want to run the tests, and only the tests, you want to comment out main. If you don't want to run the tests and run the actual game, you need to have main working and not commented out. Is your main still commented out?

Hopefully this helps.

**Comment by JustinBird** [comment]
Just checking in on if this issue is solved.
